name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo '${{ secrets.YC_SA_KEY }}' > key.json
            cat key.json | docker login --username json_key --password-stdin cr.yandex
            docker pull cr.yandex/${YC_REGISTRY_ID}/app:${{ github.event.inputs.release_version }}_latest
            docker stop shri-infra || true
            docker rm shri-infra || true
            docker run -d --name shri-infra -p 3000:3000 cr.yandex/${YC_REGISTRY_ID}/app:${{ github.event.inputs.release_version }}_latest
      - name: Comment to Issue
        run: |
          gh issue comment $(gh issue list --search "Release v${{ github.event.inputs.release_version }}" --json number --jq '.[0].number') \
            --body $'Релиз выкачен в прод: '"$(date)"$'\nАвтор: '"${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}